# -*- coding: utf-8 -*-
"""Preprocesing_And_Viualizatin_of_restaurant_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H0W3PycIz-OrBlEpu84LtJrpqBk0prZ8
"""

import pandas as pd
import numpy as np
data=pd.read_excel('/content/drive/MyDrive/Restaurant.xlsx')

data.head()

data.info()

data.isnull().sum()

d=data[data['DATE']=='01.10.23']

d.head()

d['AMOUNT'].mean()

a=data[data['INVOICE_NO']==117]

a['AMOUNT'].sum()

t=data.groupby('ITEM')['SUB_TOTAL'].sum().sort_values(ascending=False).head(5)

t.head()

import seaborn as sns

sns.barplot(t)

date=data[data['DATE']=='2.10.2023']

df=data.groupby('ITEM')['QUANTITY'].sum().sort_values(ascending=True).head(5)

sns.barplot(df)

tot=data.groupby('INVOICE_NO')['AMOUNT'].sum().sort_values(ascending=False).head(5)

tot

